# ----
# Site

title: MapBD
url: ""
baseurl: "https://mapbd.github.io/swag/"
google_analytics_key:
google_maps_javascript_api_key:
# snipcart_key: "MDM5YTczM2ItZGFlZS00ODRjLWI5MGUtYzRlMTFiYWZhOTgwNjM4NjYzNDcyMDUwMzA2MDgz"
# snipcart_currency: "usd"

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: 
description: Fur t-shirt store
author:
  name: Atikur Rahman
  email: ask@map-bd.org
  twitter:  # twitter username without the @ symbol
  phone: "+88 01723742424"
social:
  name: Fur Template
  links:
    - https://github.com/CloudCannon/fur-jekyll-template

# -----
# Build
timezone: Asia/Dhaka


collections:
  staff_members:
    output: false
  products:
    output: true

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

social_icons:
  - Email
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
